# Generated by Django 3.2.9 on 2021-12-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20211211_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='phone_number',
        ),
    ]
